---
sudo: required
language: python
services:
  - docker

addons:
  hosts:
    - zabbix-server-centos

install:
  - pip install -r requirements.txt

script:
  - molecule --version
  - ansible --version
  - molecule test -s default
  - molecule test -s with-server
