---
# tasks file for wdijkerman.zabbix

- name: "Fix facts for linuxmint - distribution release"
  set_fact:
    ansible_distribution_release: xenial
  when:
    - ansible_os_family == "Linuxmint"
    - ansible_distribution_release == "sonya" or ansible_distribution_release == "serena"

- name: "Fix facts for linuxmint - family"
  set_fact:
    ansible_os_family: Debian
  when: ansible_os_family == "Linuxmint"

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - zabbix-agent

- include: zabbix_pre_install.yml
  when: ansible_os_family != "Windows"
  tags:
    - zabbix-agent

- include: zabbix_install.yml
  when: ansible_os_family != "Windows"
  tags:
    - zabbix-agent
    - init
    - service

- include: zabbix_configure_linux.yml
  when: ansible_os_family != "Windows"

- include: zabbix_post_install.yml
  when: ansible_os_family != "Windows"
  tags:
    - zabbix-agent
    - init
    - service

- include: zabbix_install_windows.yml
  when: ansible_os_family == "Windows"

- include: zabbix_api.yml
  tags:
    - api

- name: "Including userparameters"
  include: "zabbix_userparameter.yml"
  when: zabbix_agent_userparameters|length > 0
  tags:
    - zabbix-agent
    - userparameter
