---

- name: "Installing user-defined userparameters"
  template:
    src: "{{ item.path }}/{{ item.name }}"
    dest: "{{ zabbix_agent_include }}/userparameter_{{ item.name.split('.j2')[0] }}"
    owner: zabbix
    group: zabbix
    mode: 0644
  notify: restart zabbix-agent
  become: yes
  when:
    - item.name is defined
    - item.path is defined
    - item.condition | default("True")
  with_items: "{{ zabbix_agent_userparameters }}"

- name: "Installing user-defined scripts"
  copy:
    src: "{{ item.scripts_dir }}"
    dest: "{{ item.scripts_dest | default('/etc/zabbix/scripts/') }}"
    owner: zabbix
    group: zabbix
    mode: 0755
  notify: restart zabbix-agent
  become: yes
  with_items: "{{ zabbix_agent_userparameters }}"
  when:
    - item.scripts_dir is defined
    - item.condition | default("True")

- name: "Installing user-defined system packages"
  package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ zabbix_user_packages }}"
  when: item | bool

- name: "Installing user-defined pip packages"
  pip:
    name: "{{ zabbix_user_pip_packages }}"
    state: "present"
    extra_args: "{{ zabbix_user_pip_packages_args }}"
