---

# straight to getenforce binary , workaround for missing python_selinux library
- name: "Get getenforce binary"
  stat:
    path: /usr/sbin/getenforce
  register: getenforce_bin
  become: yes

- name: "Collect getenforce output"
  command: getenforce
  register: sestatus
  when: 'getenforce_bin.stat.exists'
  changed_when: false
  become: yes
  check_mode: no

- name: "Set zabbix_selinux to true if getenforce returns Enforcing or Permissive"
  set_fact:
    zabbix_selinux: "{{ true }}"
  when: 'getenforce_bin.stat.exists and ("Enforcing" in sestatus.stdout or "Permissive" in sestatus.stdout)'

- name: "Allow zabbix_agent to start (SELinux)"
  selinux_permissive:
    name: zabbix_agent_t
    permissive: true
  become: yes
  when:
    - zabbix_selinux

- name: "Configure IPTables"
  iptables:
    destination_port: "{{ zabbix_agent_listenport }}"
    source: "{{ zabbix_agent_firewall_source | default(omit) }}"
    protocol: tcp
    chain: INPUT
    jump: ACCEPT
  become: yes
  when: zabbix_agent_firewall_enable

- name: "Configure firewalld"
  firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ zabbix_agent_firewalld_source }}" port protocol="tcp" port="{{ zabbix_agent_listenport }}" accept'
    permanent: true
    state: enabled
  become: yes
  when: zabbix_agent_firewalld_enable
  notify:
    - firewalld-reload
  tags: zabbix_agent_firewalld_enable

- name: "Make sure the zabbix-agent service is running"
  service:
    name: "{{ zabbix_agent_service }}"
    state: started
    enabled: yes
  become: yes
  tags:
    - init
    - service
