---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  flake8

platforms:
  - name: zabbix-agent-centos
    image: milcom/centos7-systemd:latest
    groups:
      - group1
    privileged: True
  - name: zabbix-agent-debian-stretch
    image: minimum2scp/systemd-stretch:latest
    command: /sbin/init
    groups:
      - group1
    privileged: True
  - name: zabbix-agent-ubuntu-xenial
    image: solita/ubuntu-systemd:xenial
    groups:
      - group1
    privileged: True
  - name: zabbix-agent-ubuntu-bionic
    image: solita/ubuntu-systemd:bionic
    groups:
      - group1
    privileged: True

provisioner:
  name: ansible

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - create
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
